version: "3.7"
services:
  characters_api:
    restart: always
    build: https://github.com/Borken/characters_microservice.git
    expose:
      - "8082"
    command: flask run --host=0.0.0.0 --port 8082
    depends_on:
      - postgres_characters
  places_api:
    restart: always
    build: https://github.com/Borken/places_microservice.git
    expose:
      - "8081"
    command: flask run --host=0.0.0.0 --port 8081
    depends_on:
      - postgres_places
  juego_de_tornos_api:
    restart: always
    build: ../juego_de_tornos_microservice
    ports:
      - "8080:8080"
    command: flask run --host=0.0.0.0 --port 8080
    depends_on:
      - places_api
      - characters_api
  postgres_characters:
    restart: always
    build: https://github.com/Borken/characters_microservice.git:postgresql
    volumes:
      - /var/lib/postgresql_characters
    expose:
      - "5432"
  postgres_places:
    restart: always
    build: https://github.com/Borken/places_microservice.git:postgresql
    volumes:
      - /var/lib/postgresql_places
    expose:
      - "5432"